# Default initial positions for rfl's ros2_control fake system

initial_positions:
  bridge1_joint_EA_X: 0
  bridge2_joint_EA_X: 0
  robot11_joint_1: 0
  robot11_joint_2: 0
  robot11_joint_3: 0
  robot11_joint_4: 0
  robot11_joint_5: 0
  robot11_joint_6: 0
  robot11_joint_EA_Y: 0
  robot11_joint_EA_Z: 0
  robot12_joint_1: 0
  robot12_joint_2: 0
  robot12_joint_3: 0
  robot12_joint_4: 0
  robot12_joint_5: 0
  robot12_joint_6: 0
  robot12_joint_EA_Y: 0
  robot12_joint_EA_Z: 0
  robot21_joint_1: 0
  robot21_joint_2: 0
  robot21_joint_3: 0
  robot21_joint_4: 0
  robot21_joint_5: 0
  robot21_joint_6: 0
  robot21_joint_EA_Y: 0
  robot21_joint_EA_Z: 0
  robot22_joint_1: 0
  robot22_joint_2: 0
  robot22_joint_3: 0
  robot22_joint_4: 0
  robot22_joint_5: 0
  robot22_joint_6: 0
  robot22_joint_EA_Y: 0
  robot22_joint_EA_Z: 0