# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - robot11_controller
    - robot12_controller
    - robot11_eaXYZ_controller
    - robot12_eaYZ_controller
    - robot21_controller
    - robot22_controller
    - robot21_eaXYZ_controller
    - robot22_eaYZ_controller
    - robot11_eaYZ_controller
    - robot21_eaYZ_controller
    - robot12_eaXYZ_controller
    - robot22_eaXYZ_controller

  robot11_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot11_joint_1
      - robot11_joint_2
      - robot11_joint_3
      - robot11_joint_4
      - robot11_joint_5
      - robot11_joint_6
  robot12_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot12_joint_1
      - robot12_joint_2
      - robot12_joint_3
      - robot12_joint_4
      - robot12_joint_5
      - robot12_joint_6
  robot11_eaXYZ_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - bridge1_joint_EA_X
      - robot11_joint_EA_Y
      - robot11_joint_EA_Z
      - robot11_joint_1
      - robot11_joint_2
      - robot11_joint_3
      - robot11_joint_4
      - robot11_joint_5
      - robot11_joint_6
  robot12_eaYZ_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot12_joint_EA_Y
      - robot12_joint_EA_Z
      - robot12_joint_1
      - robot12_joint_2
      - robot12_joint_3
      - robot12_joint_4
      - robot12_joint_5
      - robot12_joint_6
  robot21_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot21_joint_1
      - robot21_joint_2
      - robot21_joint_3
      - robot21_joint_4
      - robot21_joint_5
      - robot21_joint_6
  robot22_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot22_joint_1
      - robot22_joint_2
      - robot22_joint_3
      - robot22_joint_4
      - robot22_joint_5
      - robot22_joint_6
  robot21_eaXYZ_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - bridge2_joint_EA_X
      - robot21_joint_EA_Y
      - robot21_joint_EA_Z
      - robot21_joint_1
      - robot21_joint_2
      - robot21_joint_3
      - robot21_joint_4
      - robot21_joint_5
      - robot21_joint_6
  robot22_eaYZ_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot22_joint_EA_Y
      - robot22_joint_EA_Z
      - robot22_joint_1
      - robot22_joint_2
      - robot22_joint_3
      - robot22_joint_4
      - robot22_joint_5
      - robot22_joint_6
  robot11_eaYZ_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot11_joint_EA_Y
      - robot11_joint_EA_Z
      - robot11_joint_1
      - robot11_joint_2
      - robot11_joint_3
      - robot11_joint_4
      - robot11_joint_5
      - robot11_joint_6
  robot21_eaYZ_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot21_joint_EA_Y
      - robot21_joint_EA_Z
      - robot21_joint_1
      - robot21_joint_2
      - robot21_joint_3
      - robot21_joint_4
      - robot21_joint_5
      - robot21_joint_6
  robot12_eaXYZ_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - bridge1_joint_EA_X
      - robot12_joint_EA_Y
      - robot12_joint_EA_Z
      - robot12_joint_1
      - robot12_joint_2
      - robot12_joint_3
      - robot12_joint_4
      - robot12_joint_5
      - robot12_joint_6
  robot22_eaXYZ_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - bridge2_joint_EA_X
      - robot22_joint_EA_Y
      - robot22_joint_EA_Z
      - robot22_joint_1
      - robot22_joint_2
      - robot22_joint_3
      - robot22_joint_4
      - robot22_joint_5
      - robot22_joint_6